"""
产品库种子数据

首次启动（products 表为空）时，把前端 MOCK_PRODUCTS 的 6 条产品预置到 PG，
确保演示时产品库打开即有真实数据。

数据来源：frontend/src/stores/productLibrary.ts 的 MOCK_PRODUCTS。
"""

from sqlalchemy import select, func
from core.database import async_session_factory
from modules.products.db_model import SpuRecord, SkuRecord

SEED_PRODUCTS = [
    {
        "id": "prod-000",
        "asin": "B0CEXIZ001",
        "sku": "SKU-BL-000",
        "title": "Portable Mini Humidifier for Bedroom Desk USB Cool Mist",
        "brand": "CoolMist",
        "category": "home",
        "sub_category": "加湿器",
        "price": 24.99,
        "cost": 14.48,
        "currency": "USD",
        "listing_status": "draft",
        "bsr": None,
        "rating": 0,
        "review_count": 0,
        "main_image": "https://picsum.photos/seed/B0CEXIZ001/600/600",
        "images": [
            "https://picsum.photos/seed/B0CEXIZ001-a/600/600",
            "https://picsum.photos/seed/B0CEXIZ001-b/600/600",
        ],
        "variation_parent": None,
        "variation_theme": None,
        "variations": [],
        "fba_stock": 0,
        "fbm_stock": 0,
        "fulfillment_type": "FBA",
        "daily_sales_avg": 0,
        "roi": 0,
        "margin": 26,
        "shop_id": "shop-1",
        "tags": ["蓝海", "新品"],
        "notes": "从蓝海挖掘保存的草稿，待 Listing 优化",
        "status": "draft",
        "groups": [],
        "selling_points": "500ml 大容量水箱，整夜加湿无需加水 | 双雾量模式（持续/间歇）适应不同场景 | USB 供电 + 静音运行，办公/卧室两不误 | 智能自动断电保护，水位低自动停机 | 顶置注水口，无需拆机加水",
        "keywords": ["mini humidifier", "usb humidifier", "bedroom humidifier", "cool mist humidifier", "desktop humidifier"],
        "generated_title": "Portable Mini Humidifier for Bedroom Desk USB Cool Mist, 500ml Top-Fill Ultra-Quiet 25dB Auto Shut-Off, Dual Mist Modes for Office Baby Room",
        "generated_bullets": [
            {"title": "500ML LARGE CAPACITY & TOP-FILL DESIGN", "content": "Top-fill 500ml tank delivers up to 10 hours of continuous cool mist without refilling; simply flip the lid to add water — no disassembly needed, even when the unit is running."},
            {"title": "2 MIST MODES & ULTRA-QUIET 25dB", "content": "Switch between continuous mist for fast humidifying and intermittent mist for overnight use; ultrasonic whisper-quiet operation ensures undisturbed sleep, study or work."},
            {"title": "USB POWERED & AUTO SHUT-OFF", "content": "Powered by any 5V USB source — laptop, power bank, USB adapter — perfect for desk, dorm, travel; built-in sensor automatically powers off when water runs low to protect the unit."},
            {"title": "PORTABLE COMPACT FOR ANY SPACE", "content": "5.5 × 5.5 × 7 inch compact footprint fits any bedside table, office desk or nursery; lightweight 0.8 lb design makes it easy to move between rooms."},
            {"title": "NIGHT LIGHT & GIFT-READY", "content": "Soft warm LED night light creates a cozy atmosphere; FDA-grade BPA-free materials, ideal gift for new parents, office workers, and students."},
        ],
        "description": "The AquaMist Portable Mini Humidifier is your personal moisture companion. Featuring a 500ml top-fill tank and dual mist modes, it delivers up to 10 hours of whisper-quiet (25dB) cool mist to relieve dry skin, chapped lips, and static.",
        "seo_score": 68,
        "listing_version": 1,
        "competitor_asins": ["B0BQVCKZDG", "B08XYZ1234", "B09ABC5678"],
        "has_a_plus": False,
        "has_video": False,
        "rating_breakdown": {"5": 0, "4": 0, "3": 0, "2": 0, "1": 0},
        "created_at": "2026-09-01T07:00:00Z",
    },
    {
        "id": "prod-001",
        "asin": "B0DGXRLVLC",
        "sku": "SKU-WL-001",
        "title": "无线蓝牙耳机 降噪头戴式 长续航40小时 HiFi音质",
        "brand": "SoundMax",
        "category": "electronics",
        "sub_category": "耳机/音响",
        "price": 49.99,
        "cost": 18.50,
        "currency": "USD",
        "listing_status": "active",
        "bsr": 1234,
        "rating": 4.6,
        "review_count": 2890,
        "main_image": "https://picsum.photos/seed/B0DGXRLVLC/600/600",
        "images": [
            "https://picsum.photos/seed/B0DGXRLVLC-a/600/600",
            "https://picsum.photos/seed/B0DGXRLVLC-b/600/600",
            "https://picsum.photos/seed/B0DGXRLVLC-c/600/600",
        ],
        "variation_parent": None,
        "variation_theme": None,
        "variations": [
            {"asin": "B0DGXRLVLC", "color": "黑色", "price": 49.99, "stock": 450},
            {"asin": "B0DGXRLVLD", "color": "白色", "price": 49.99, "stock": 320},
        ],
        "fba_stock": 770,
        "fbm_stock": 0,
        "fulfillment_type": "FBA",
        "daily_sales_avg": 45,
        "roi": 170,
        "margin": 63,
        "shop_id": "shop-1",
        "tags": ["热销", "新品", "Prime"],
        "notes": "Q4 主推款，已开广告",
        "status": "active",
        "groups": [],
        "selling_points": "主动降噪深度 -35dB，打造沉浸音场 | 蓝牙 5.3 稳定连接，延迟低至 60ms | 40 小时超长续航，满足一周通勤 | 40mm 大动圈 HiFi 音质，三频均衡 | 可折叠设计，附硬壳收纳包",
        "keywords": ["wireless headphone", "bluetooth headphone", "noise cancelling", "over ear headphone", "long battery headphone"],
        "generated_title": "SoundMax Wireless Bluetooth Headphones Over-Ear, Active Noise Cancelling -35dB, 40H Playtime HiFi Stereo Sound, Foldable Travel Headset with Built-in Mic",
        "generated_bullets": [
            {"title": "ACTIVE NOISE CANCELLING -35dB", "content": "Dual-mic ANC technology detects and cancels ambient noise up to -35dB, perfect for flights, commutes, and busy offices; transparent mode lets you hear surroundings with one tap."},
            {"title": "BLUETOOTH 5.3 & 60ms LOW LATENCY", "content": "Bluetooth 5.3 delivers stable, fast pairing up to 33ft with no audio drop; 60ms ultra-low latency mode optimized for gaming and video, perfectly synced with action."},
            {"title": "40-HOUR LONG BATTERY LIFE", "content": "Get up to 40 hours of playtime on a single charge (ANC off) — enough for a full week of commuting; 10-minute quick charge provides 3 hours of playback."},
            {"title": "HiFi 40MM DRIVERS & DEEP BASS", "content": "Custom-tuned 40mm drivers reproduce rich, detailed sound with deep bass and clear vocals; Hi-Res Audio certified for premium listening experience."},
            {"title": "FOLDABLE & TRAVEL-READY", "content": "Memory-foam earcups with adjustable headband fit all-day comfort; foldable design with included hard carrying case slips easily into backpack or carry-on."},
        ],
        "description": "Experience your music the way it was meant to be heard. The SoundMax ANC Wireless Headphones combine studio-quality HiFi sound with industry-leading -35dB active noise cancellation.",
        "seo_score": 86,
        "listing_version": 1,
        "competitor_asins": ["B0CHJ7X31P", "B07XX12NO3", "B09XYZAB12"],
        "has_a_plus": True,
        "has_video": True,
        "rating_breakdown": {"5": 1890, "4": 620, "3": 240, "2": 90, "1": 50},
        "created_at": "2026-07-15T10:00:00Z",
    },
    {
        "id": "prod-002",
        "asin": "B0ABC12345",
        "sku": "SKU-KC-002",
        "title": "智能保温杯 温度显示 304不锈钢 大容量500ml",
        "brand": "ThermoPro",
        "category": "home",
        "sub_category": "厨房用品",
        "price": 29.99,
        "cost": 9.80,
        "currency": "USD",
        "listing_status": "active",
        "bsr": 5678,
        "rating": 4.3,
        "review_count": 1256,
        "main_image": "https://picsum.photos/seed/B0ABC12345/600/600",
        "images": [
            "https://picsum.photos/seed/B0ABC12345-a/600/600",
            "https://picsum.photos/seed/B0ABC12345-b/600/600",
        ],
        "variation_parent": None,
        "variation_theme": "Color",
        "variations": [
            {"asin": "B0ABC12345", "color": "银色", "price": 29.99, "stock": 200},
            {"asin": "B0ABC12346", "color": "玫瑰金", "price": 32.99, "stock": 150},
            {"asin": "B0ABC12347", "color": "黑色", "price": 29.99, "stock": 180},
        ],
        "fba_stock": 530,
        "fbm_stock": 0,
        "fulfillment_type": "FBA",
        "daily_sales_avg": 28,
        "roi": 206,
        "margin": 67,
        "shop_id": "shop-1",
        "tags": ["热销", "礼品"],
        "notes": "冬季主推，库存充足",
        "status": "active",
        "groups": [],
        "selling_points": "智能 LED 温度显示，喝水一目了然 | 304 双层不锈钢真空，保冷 24h / 保温 12h | 500ml 大容量，单手开盖设计 | BPA-free 安全材质，无异味 | 防漏防烫杯口，可单手操作",
        "keywords": ["smart water bottle", "insulated water bottle", "temperature display bottle", "stainless steel bottle", "gift water bottle"],
        "generated_title": "ThermoPro Smart Water Bottle 500ml with LED Temperature Display, 24H Cold 12H Hot 304 Stainless Steel Double-Wall Vacuum, BPA-Free Leak-Proof Sport Bottle",
        "generated_bullets": [
            {"title": "LED TEMPERATURE DISPLAY", "content": "Smart touch-cap shows real-time water temperature on a hidden LED screen — never burn your tongue again; one-tap to check without removing the lid."},
            {"title": "24H COLD & 12H HOT INSULATION", "content": "Premium double-wall 304 stainless steel vacuum insulation keeps drinks ice-cold for 24 hours and piping-hot for 12 hours; tested and proven for daily commutes and outdoor use."},
            {"title": "ONE-HAND OPERATION", "content": "Push-button release with built-in locking mechanism opens the lid with a single finger — perfect for driving, cycling, and gym workouts; spill-proof even when tilted."},
            {"title": "BPA-FREE & ODOR-FREE", "content": "Made of food-grade 304 stainless steel inside and out; BPA-free, phthalate-free, won't retain flavors or odors from yesterday's coffee."},
            {"title": "500ML PORTABLE & GIFT-READY", "content": "Slim 500ml design fits standard car cup holders and backpack side pockets; comes in premium gift box — perfect gift for fitness lovers, students, and office workers."},
        ],
        "description": "Drink smarter with the ThermoPro Smart Water Bottle. The built-in LED temperature display shows you the exact temperature of your drink with a single tap.",
        "seo_score": 78,
        "listing_version": 1,
        "competitor_asins": ["B0BPABCXYZ", "B07WAQ12MN", "B09COLD789"],
        "has_a_plus": True,
        "has_video": False,
        "rating_breakdown": {"5": 720, "4": 380, "3": 120, "2": 26, "1": 10},
        "created_at": "2026-08-01T09:00:00Z",
    },
    {
        "id": "prod-003",
        "asin": "B0DEF67890",
        "sku": "SKU-BP-003",
        "title": "电动牙刷 成人声波震动 5档模式 IPX7防水 续航90天",
        "brand": "CleanTech",
        "category": "beauty",
        "sub_category": "口腔护理",
        "price": 24.99,
        "cost": 8.20,
        "currency": "USD",
        "listing_status": "active",
        "bsr": 3456,
        "rating": 4.5,
        "review_count": 3420,
        "main_image": "https://picsum.photos/seed/B0DEF67890/600/600",
        "images": [
            "https://picsum.photos/seed/B0DEF67890-a/600/600",
            "https://picsum.photos/seed/B0DEF67890-b/600/600",
            "https://picsum.photos/seed/B0DEF67890-c/600/600",
        ],
        "variation_parent": None,
        "variation_theme": "Color",
        "variations": [
            {"asin": "B0DEF67890", "color": "白色", "price": 24.99, "stock": 600},
            {"asin": "B0DEF67891", "color": "粉色", "price": 26.99, "stock": 400},
        ],
        "fba_stock": 1000,
        "fbm_stock": 50,
        "fulfillment_type": "FBA",
        "daily_sales_avg": 62,
        "roi": 204,
        "margin": 67,
        "shop_id": "shop-1",
        "tags": ["爆款", "Prime", "广告中"],
        "notes": "ACoS 控制在 18%，ROI 表现优秀",
        "status": "active",
        "groups": [],
        "selling_points": "声波震动 38000 次/分钟，深层清洁牙菌斑 | 5 档模式（清洁/美白/敏感/抛光/按摩）满足全家需求 | IPX7 整机防水，洗澡也能用 | 续航 90 天，一年只需充 4 次电 | 杜邦软毛刷头，呵护敏感牙龈",
        "keywords": ["electric toothbrush", "sonic toothbrush", "rechargeable toothbrush", "waterproof toothbrush", "oral care"],
        "generated_title": "CleanTech Rechargeable Sonic Electric Toothbrush for Adults, 38000 VPM 5 Modes IPX7 Waterproof, 90 Days Battery Life with 8 DuPont Brush Heads",
        "generated_bullets": [
            {"title": "38000 VPM SONIC CLEANING", "content": "High-frequency sonic vibrations drive toothpaste foam deep between teeth and along the gum line, removing up to 7× more plaque than a manual brush — dentists-recommended."},
            {"title": "5 BRUSHING MODES FOR EVERY NEED", "content": "Clean / White / Sensitive / Polish / Massage modes cover everything from daily cleaning to gum care; built-in 2-minute timer with 30-second pacer keeps you on track."},
            {"title": "IPX7 WATERPROOF & SHOWER-SAFE", "content": "Fully sealed IPX7 body means you can rinse it directly under the faucet — or even use it in the shower; ideal for bathroom humid environments."},
            {"title": "90-DAY BATTERY LIFE", "content": "One full charge lasts up to 90 days of regular use (2 min × 2/day) on a single USB charge; included 8 DuPont soft-bristle replacement heads cover 2+ years of use."},
            {"title": "FAMILY-FRIENDLY DESIGN", "content": "Ergonomic non-slip grip with anti-skid silicone; 4 color-coded brush heads make it easy to share among family members; quiet motor under 55dB for early mornings."},
        ],
        "description": "Upgrade your oral care routine with the CleanTech Sonic Electric Toothbrush. 38000 vibrations per minute remove up to 7× more plaque than a manual brush.",
        "seo_score": 84,
        "listing_version": 1,
        "competitor_asins": ["B0CCLEAN01", "B09ORALB12", "B0BFRESH99"],
        "has_a_plus": True,
        "has_video": True,
        "rating_breakdown": {"5": 2100, "4": 920, "3": 280, "2": 80, "1": 40},
        "created_at": "2026-06-20T08:00:00Z",
    },
    {
        "id": "prod-004",
        "asin": "B0GHI23456",
        "sku": "SKU-YG-004",
        "title": "瑜伽垫 加厚10mm 双面防滑 TPE环保 无味",
        "brand": "FlexFit",
        "category": "sports",
        "sub_category": "瑜伽/健身",
        "price": 19.99,
        "cost": 5.50,
        "currency": "USD",
        "listing_status": "active",
        "bsr": 8901,
        "rating": 4.2,
        "review_count": 876,
        "main_image": "https://picsum.photos/seed/B0GHI23456/600/600",
        "images": [
            "https://picsum.photos/seed/B0GHI23456-a/600/600",
            "https://picsum.photos/seed/B0GHI23456-b/600/600",
        ],
        "variation_parent": None,
        "variation_theme": None,
        "variations": [],
        "fba_stock": 350,
        "fbm_stock": 100,
        "fulfillment_type": "FBA",
        "daily_sales_avg": 18,
        "roi": 263,
        "margin": 72,
        "shop_id": "shop-1",
        "tags": ["新品", "轻量"],
        "notes": "新上架两周，正在积累评论",
        "status": "active",
        "groups": [],
        "selling_points": "10mm 加厚设计，跪姿不痛、跳跃缓冲足 | 双面防滑纹理，平衡体式不滑动 | TPE 环保材质，无异味可直接使用 | 6 尺寸 / 6 色可选，全家可用 | 易卷起收纳，背面附携带带",
        "keywords": ["yoga mat", "thick yoga mat", "non slip yoga mat", "tpe yoga mat", "eco friendly yoga mat"],
        "generated_title": "FlexFit Yoga Mat 10mm Thick Extra Cushion, Double-Sided Non-Slip TPE Eco-Friendly Odorless Exercise Mat with Carry Strap for Pilates Home Workout",
        "generated_bullets": [
            {"title": "EXTRA THICK 10MM CUSHION", "content": "10mm high-density foam provides superior joint protection — knees, elbows, hips and spine stay comfortable through kneeling poses and high-impact HIIT; much thicker than standard 6mm mats."},
            {"title": "DOUBLE-SIDED NON-SLIP GRIP", "content": "Diamond-textured top layer locks your hands and feet in place during downward dog and balance poses; ribbed bottom grips the floor and stays put on hardwood, tile, or carpet."},
            {"title": "TPE ECO-FRIENDLY ODORLESS", "content": "Premium TPE material is free from PVC, latex, and harmful plasticizers — no chemical smell, safe for kids and sensitive skin; certified by SGS, RoHS and REACH."},
            {"title": "6 SIZES & 6 COLORS AVAILABLE", "content": "Choose from 6 sizes (68\"/72\"/74\" × 24\"/48\"/72\") and 6 colors to fit every family member — perfect for solo, partner, or wide-format workouts."},
            {"title": "LIGHTWEIGHT & TRAVEL-FRIENDLY", "content": "Only 2.2 lbs — half the weight of traditional rubber mats; built-in carry strap makes it easy to roll up and take to studio, gym, or outdoor yoga."},
        ],
        "description": "Practice with confidence on the FlexFit 10mm Yoga Mat. Extra-thick high-density foam cushions your joints through kneeling, plank, and high-impact moves.",
        "seo_score": 72,
        "listing_version": 1,
        "competitor_asins": ["B09FLEX001", "B07YOGAX12", "B0CMAT203"],
        "has_a_plus": False,
        "has_video": True,
        "rating_breakdown": {"5": 480, "4": 290, "3": 80, "2": 18, "1": 8},
        "created_at": "2026-08-15T12:00:00Z",
    },
    {
        "id": "prod-005",
        "asin": "B0JKL78901",
        "sku": "SKU-CM-005",
        "title": "男士运动速干T恤 圆领透气 吸湿排汗 健身跑步",
        "brand": "ActiveWear",
        "category": "clothing",
        "sub_category": "男装/T恤",
        "price": 15.99,
        "cost": 4.20,
        "currency": "USD",
        "listing_status": "active",
        "bsr": 15234,
        "rating": 4.1,
        "review_count": 2340,
        "main_image": "https://picsum.photos/seed/B0JKL78901/600/600",
        "images": [
            "https://picsum.photos/seed/B0JKL78901-a/600/600",
            "https://picsum.photos/seed/B0JKL78901-b/600/600",
            "https://picsum.photos/seed/B0JKL78901-c/600/600",
        ],
        "variation_parent": None,
        "variation_theme": "Size",
        "variations": [
            {"asin": "B0JKL78901", "size": "M", "price": 15.99, "stock": 300},
            {"asin": "B0JKL78902", "size": "L", "price": 15.99, "stock": 280},
            {"asin": "B0JKL78903", "size": "XL", "price": 17.99, "stock": 200},
            {"asin": "B0JKL78904", "size": "XXL", "price": 17.99, "stock": 120},
        ],
        "fba_stock": 900,
        "fbm_stock": 0,
        "fulfillment_type": "FBA",
        "daily_sales_avg": 85,
        "roi": 280,
        "margin": 74,
        "shop_id": "shop-1",
        "tags": ["爆款", "高周转"],
        "notes": "变体齐全，S码断货补货中",
        "status": "active",
        "groups": [],
        "selling_points": "5 秒速干面料，集训出汗也不贴身 | 99% 涤纶 + 1% 氨纶，四面弹力不束缚 | UPF 50+ 防紫外线，户外跑步防晒伤 | 五线平整缝线 + 标签外印，不磨皮肤 | 4 色×4 码（M-L-XL-XXL）全尺码可选",
        "keywords": ["mens running shirt", "quick dry tshirt", "sport t shirt", "moisture wicking shirt", "gym shirt"],
        "generated_title": "ActiveWear Men's Quick Dry Running T-Shirt, 5s Moisture-Wicking UPF 50+ Sun Protection 4-Way Stretch Activewear for Gym Training Running",
        "generated_bullets": [
            {"title": "5-SEC MOISTURE WICKING", "content": "High-performance moisture-wicking fabric pulls sweat away from your skin and evaporates in 5 seconds — stay dry and comfortable through the toughest workouts."},
            {"title": "4-WAY STRETCH COMFORT", "content": "Premium 99% polyester + 1% spandex blend moves with you in every direction; no restriction during sprints, lifts, or yoga flows."},
            {"title": "UPF 50+ SUN PROTECTION", "content": "Built-in UV protection blocks over 98% of harmful UVA/UVB rays — wear it for outdoor runs, hikes, or fishing without worrying about sunburn."},
            {"title": "FLATLOCK SEAMS & TAGLESS", "content": "Flat-stitched seams reduce chafing and skin irritation during long workouts; tagless printed neck label eliminates the scratch of traditional tags."},
            {"title": "4 SIZES & MULTIPLE COLORS", "content": "Available from M to XXL and in 4 versatile colors (Black/Gray/White/Navy); fits true to size — size up for an athletic loose fit."},
        ],
        "description": "Train harder in the ActiveWear Quick Dry Running T-Shirt. Advanced moisture-wicking fabric pulls sweat away from your skin and evaporates it in just 5 seconds.",
        "seo_score": 80,
        "listing_version": 1,
        "competitor_asins": ["B0BRUN99X", "B07TSHIRT1", "B09ATHLET1"],
        "has_a_plus": False,
        "has_video": False,
        "rating_breakdown": {"5": 1280, "4": 760, "3": 230, "2": 50, "1": 20},
        "created_at": "2026-05-10T10:00:00Z",
    },
]


async def seed_products_if_empty() -> int:
    """首次启动时，若 spus 表为空，预置种子数据（SPU + SKU 分表）。返回预置 SPU 条数。"""
    async with async_session_factory() as session:
        count = (await session.execute(select(func.count()).select_from(SpuRecord))).scalar_one()
        if count > 0:
            return 0
        for data in SEED_PRODUCTS:
            spu_id = data["id"]
            spu = SpuRecord(
                id=spu_id,
                title=data["title"],
                brand=data["brand"],
                category=data["category"],
                sub_category=data["sub_category"],
                spu_theme=data.get("variation_theme"),
                keywords=data.get("keywords"),
                selling_points=data.get("selling_points"),
                description=data.get("description"),
                main_image=data["main_image"],
                images=data["images"],
                spu_common={
                    "brand": data["brand"],
                    "category": data["category"],
                    "keywords": data.get("keywords") or [],
                    "selling_points": data.get("selling_points") or "",
                    "bullets": data.get("generated_bullets") or [],
                    "a_plus": None,
                },
                shop_id=data["shop_id"],
                tags=data["tags"],
                notes=data["notes"],
                status=data["status"],
                groups=data["groups"],
                created_at=data["created_at"],
                updated_at=data["created_at"],
            )
            session.add(spu)

            # 有变体清单则拆成对应 SKU；否则生成一条无规格的默认 SKU
            variations = data.get("variations") or []
            if variations:
                for i, v in enumerate(variations):
                    spec = v.get("color") or v.get("size") or ""
                    session.add(SkuRecord(
                        id=f"{spu_id}-sku-{i}",
                        spu_id=spu_id,
                        spec_value=spec,
                        asin=v["asin"],
                        sku_code=data.get("sku") or f"SKU-{v['asin']}",
                        price=v.get("price", data["price"]),
                        cost=data["cost"],
                        currency=data["currency"],
                        fba_stock=v.get("stock", 0),
                        fbm_stock=0,
                        fulfillment_type=data.get("fulfillment_type", "FBA"),
                        bsr=data.get("bsr"),
                        rating=data.get("rating", 0),
                        review_count=data.get("review_count", 0),
                        daily_sales_avg=data.get("daily_sales_avg", 0),
                        roi=data.get("roi", 0),
                        margin=data.get("margin", 0),
                        listing_status=data.get("listing_status", "draft"),
                        generated_title=data.get("generated_title"),
                        generated_bullets=data.get("generated_bullets"),
                        generated_a_plus=None,
                        seo_score=data.get("seo_score"),
                        listing_version=data.get("listing_version", 1),
                        has_a_plus=data.get("has_a_plus", False),
                        has_video=data.get("has_video", False),
                        rating_breakdown=data.get("rating_breakdown"),
                        tags=data["tags"],
                        notes=data["notes"],
                        status=data["status"],
                        created_at=data["created_at"],
                        updated_at=data["created_at"],
                    ))
            else:
                session.add(SkuRecord(
                    id=f"{spu_id}-sku-0",
                    spu_id=spu_id,
                    spec_value=None,
                    asin=data["asin"],
                    sku_code=data.get("sku") or f"SKU-{data['asin']}",
                    price=data["price"],
                    cost=data["cost"],
                    currency=data["currency"],
                    fba_stock=data.get("fba_stock", 0),
                    fbm_stock=data.get("fbm_stock", 0),
                    fulfillment_type=data.get("fulfillment_type", "FBA"),
                    bsr=data.get("bsr"),
                    rating=data.get("rating", 0),
                    review_count=data.get("review_count", 0),
                    daily_sales_avg=data.get("daily_sales_avg", 0),
                    roi=data.get("roi", 0),
                    margin=data.get("margin", 0),
                    listing_status=data.get("listing_status", "draft"),
                    generated_title=data.get("generated_title"),
                    generated_bullets=data.get("generated_bullets"),
                    generated_a_plus=None,
                    seo_score=data.get("seo_score"),
                    listing_version=data.get("listing_version", 1),
                    has_a_plus=data.get("has_a_plus", False),
                    has_video=data.get("has_video", False),
                    rating_breakdown=data.get("rating_breakdown"),
                    tags=data["tags"],
                    notes=data["notes"],
                    status=data["status"],
                    created_at=data["created_at"],
                    updated_at=data["created_at"],
                ))
        await session.commit()
    return len(SEED_PRODUCTS)
