"""baseline: full schema (squashed)

Revision ID: 0d44a915bbb8
Revises: 
Create Date: 2026-09-15 16:16:03.582025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d44a915bbb8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conv_msg_conversation_seq', 'conversation_messages', ['conversation_id', 'seq'], unique=False)
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('price_monthly', sa.Float(), nullable=False),
    sa.Column('api_calls_limit', sa.Integer(), nullable=False),
    sa.Column('agent_chat_limit', sa.Integer(), nullable=False),
    sa.Column('max_shops', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('features', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('pdf_url', sa.String(length=512), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_invoices_idempotency_key'), 'invoices', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.create_table('payment_methods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=32), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('exp_month', sa.Integer(), nullable=False),
    sa.Column('exp_year', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_user_id'), 'payment_methods', ['user_id'], unique=False)
    op.create_table('shops',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.Enum('AMAZON_US', 'AMAZON_UK', 'TIKTOK', 'SHOPIFY', name='shopplatform'), nullable=False),
    sa.Column('seller_id', sa.String(length=255), nullable=True),
    sa.Column('marketplace_id', sa.String(length=20), nullable=True),
    sa.Column('api_credentials', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_owner_id'), 'shops', ['owner_id'], unique=False)
    op.create_table('stores_store',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('marketplace_id', sa.String(length=64), nullable=True),
    sa.Column('region_code', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('fee_template_id', sa.String(length=64), nullable=True),
    sa.Column('discount_template_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('connection_status', sa.String(length=16), nullable=False),
    sa.Column('sync_status', sa.String(length=16), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('has_credentials', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fk_stores_store_owner_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_store_owner_id'), 'stores_store', ['owner_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('billing_cycle', sa.String(length=10), server_default='monthly', nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('api_calls_used', sa.Integer(), nullable=False),
    sa.Column('agent_chats_used', sa.Integer(), nullable=False),
    sa.Column('llm_tokens_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('llm_cost_used', sa.Float(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('aigc_jobs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('user_id', sa.String(length=36), server_default='', nullable=False),
    sa.Column('shop_id', sa.String(length=64), server_default='', nullable=False),
    sa.Column('request_id', sa.String(length=64), server_default='', nullable=False),
    sa.Column('dedupe_key', sa.String(length=128), server_default='', nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), server_default='', nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), server_default='', nullable=False),
    sa.Column('assets_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('retries', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['stores_store.id'], name='fk_aigc_jobs_shop_id_stores_store', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aigc_jobs_dedupe_key'), 'aigc_jobs', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_aigc_jobs_kind'), 'aigc_jobs', ['kind'], unique=False)
    op.create_index(op.f('ix_aigc_jobs_shop_id'), 'aigc_jobs', ['shop_id'], unique=False)
    op.create_index(op.f('ix_aigc_jobs_status'), 'aigc_jobs', ['status'], unique=False)
    op.create_index('ix_aigc_jobs_user_created', 'aigc_jobs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_aigc_jobs_user_id'), 'aigc_jobs', ['user_id'], unique=False)
    op.create_index('uq_aigc_jobs_inflight', 'aigc_jobs', ['user_id', 'dedupe_key'], unique=True, postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.create_table('amazon_ad_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('granularity', sa.String(length=16), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('campaign_name', sa.String(length=256), nullable=True),
    sa.Column('ad_group_id', sa.String(length=64), nullable=True),
    sa.Column('ad_group_name', sa.String(length=256), nullable=True),
    sa.Column('targeting_type', sa.String(length=32), nullable=True),
    sa.Column('keyword_text', sa.String(length=256), nullable=True),
    sa.Column('target_id', sa.String(length=128), nullable=True),
    sa.Column('target_expression', sa.String(length=512), nullable=True),
    sa.Column('asin', sa.String(length=16), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('cpc', sa.Float(), nullable=False),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('units_sold', sa.Integer(), nullable=False),
    sa.Column('sales', sa.Float(), nullable=False),
    sa.Column('cvr', sa.Float(), nullable=False),
    sa.Column('acos', sa.Float(), nullable=False),
    sa.Column('roas', sa.Float(), nullable=False),
    sa.Column('cpa', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores_store.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'date', 'report_type', 'campaign_id', 'keyword_text', 'target_id', 'asin', name='uq_ad_metric_unique')
    )
    op.create_index('ix_ad_metrics_asin', 'amazon_ad_metrics', ['store_id', 'asin'], unique=False)
    op.create_index('ix_ad_metrics_campaign', 'amazon_ad_metrics', ['store_id', 'campaign_id'], unique=False)
    op.create_index('ix_ad_metrics_report_type', 'amazon_ad_metrics', ['store_id', 'report_type'], unique=False)
    op.create_index('ix_ad_metrics_store_date', 'amazon_ad_metrics', ['store_id', 'date'], unique=False)
    op.create_table('amazon_auth_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores_store.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_amazon_auth_logs_action', 'amazon_auth_logs', ['action'], unique=False)
    op.create_index('ix_amazon_auth_logs_created', 'amazon_auth_logs', ['created_at'], unique=False)
    op.create_index('ix_amazon_auth_logs_store_id', 'amazon_auth_logs', ['store_id'], unique=False)
    op.create_table('amazon_competitor_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('competitor_asin', sa.String(length=16), nullable=False),
    sa.Column('brand', sa.String(length=256), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('competes_with_asin', sa.String(length=16), nullable=True, comment='关联的自研产品 ASIN'),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_vs_own', sa.Float(), nullable=True, comment='与自研产品的价差（正=竞品更贵，负=竞品更便宜）'),
    sa.Column('price_change', sa.String(length=32), nullable=True, comment='PRICE_DROP / PRICE_HIKE / STABLE / NORMAL_FLUCT'),
    sa.Column('has_buybox', sa.Boolean(), nullable=True),
    sa.Column('buybox_price', sa.Float(), nullable=True),
    sa.Column('bsr_rank', sa.Integer(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('fulfillment', sa.String(length=32), nullable=True),
    sa.Column('main_image_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores_store.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'snapshot_date', 'competitor_asin', name='uq_competitor_snapshot_unique')
    )
    op.create_index('ix_comp_snap_brand', 'amazon_competitor_snapshots', ['brand'], unique=False)
    op.create_index('ix_comp_snap_competes', 'amazon_competitor_snapshots', ['store_id', 'competes_with_asin'], unique=False)
    op.create_index('ix_comp_snap_store_date', 'amazon_competitor_snapshots', ['store_id', 'snapshot_date'], unique=False)
    op.create_table('amazon_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('seller_id', sa.String(length=32), nullable=True),
    sa.Column('marketplace_participant_id', sa.String(length=64), nullable=True),
    sa.Column('aws_region', sa.String(length=32), nullable=False),
    sa.Column('api_endpoint', sa.String(length=256), nullable=True),
    sa.Column('credential_status', sa.String(length=16), nullable=False),
    sa.Column('last_refresh_at', sa.DateTime(), nullable=True),
    sa.Column('refresh_error', sa.Text(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores_store.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_index('ix_amazon_creds_status', 'amazon_credentials', ['credential_status'], unique=False)
    op.create_index('ix_amazon_creds_store_id', 'amazon_credentials', ['store_id'], unique=False)
    op.create_table('amazon_daily_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('asin', sa.String(length=16), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('product_name', sa.String(length=512), nullable=True),
    sa.Column('units_ordered', sa.Integer(), nullable=False),
    sa.Column('units_refunded', sa.Integer(), nullable=False),
    sa.Column('units_shipped', sa.Integer(), nullable=False),
    sa.Column('ordered_revenue', sa.Float(), nullable=False),
    sa.Column('refund_amount', sa.Float(), nullable=False),
    sa.Column('net_revenue', sa.Float(), nullable=False),
    sa.Column('ordered_revenue_usd', sa.Float(), nullable=True),
    sa.Column('net_revenue_usd', sa.Float(), nullable=True),
    sa.Column('estimated_fees', sa.Float(), nullable=True),
    sa.Column('estimated_fba_fee', sa.Float(), nullable=True),
    sa.Column('estimated_ad_spend', sa.Float(), nullable=True),
    sa.Column('estimated_profit', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('bsr_rank', sa.Integer(), nullable=True),
    sa.Column('buybox_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores_store.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'date', 'asin', name='uq_daily_sales_store_date_asin')
    )
    op.create_index('ix_daily_sales_asin', 'amazon_daily_sales', ['asin'], unique=False)
    op.create_index('ix_daily_sales_date', 'amazon_daily_sales', ['date'], unique=False)
    op.create_index('ix_daily_sales_store_date', 'amazon_daily_sales', ['store_id', 'date'], unique=False)
    op.create_table('amazon_inventory_health',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('asin', sa.String(length=16), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('fn_sku', sa.String(length=64), nullable=True),
    sa.Column('product_name', sa.String(length=512), nullable=True),
    sa.Column('fulfillable_quantity', sa.Integer(), nullable=False),
    sa.Column('inbound_working_quantity', sa.Integer(), nullable=False),
    sa.Column('inbound_shipped_quantity', sa.Integer(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('days_supply', sa.Integer(), nullable=True),
    sa.Column('aged_30_days', sa.Integer(), nullable=True),
    sa.Column('aged_61_90_days', sa.Integer(), nullable=True),
    sa.Column('aged_91_180_days', sa.Integer(), nullable=True),
    sa.Column('aged_181_270_days', sa.Integer(), nullable=True),
    sa.Column('aged_271_365_days', sa.Integer(), nullable=True),
    sa.Column('aged_365_plus_days', sa.Integer(), nullable=True),
    sa.Column('is_stagnant', sa.Boolean(), nullable=False),
    sa.Column('has_stockout_risk', sa.Boolean(), nullable=False),
    sa.Column('health_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores_store.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'snapshot_date', 'asin', name='uq_inventory_health_unique')
    )
    op.create_index('ix_inv_health_stagnant', 'amazon_inventory_health', ['store_id', 'is_stagnant'], unique=False)
    op.create_index('ix_inv_health_stockout', 'amazon_inventory_health', ['store_id', 'has_stockout_risk'], unique=False)
    op.create_index('ix_inv_health_store_date', 'amazon_inventory_health', ['store_id', 'snapshot_date'], unique=False)
    op.create_table('amazon_listing_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('asin', sa.String(length=16), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('brand', sa.String(length=256), nullable=True),
    sa.Column('manufacturer', sa.String(length=256), nullable=True),
    sa.Column('product_type', sa.String(length=256), nullable=True),
    sa.Column('condition_type', sa.String(length=32), nullable=True),
    sa.Column('item_package_quantity', sa.Integer(), nullable=True),
    sa.Column('number_of_items', sa.Integer(), nullable=True),
    sa.Column('standard_price', sa.Float(), nullable=True),
    sa.Column('buybox_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('fulfillment_channel', sa.String(length=32), nullable=True),
    sa.Column('available_quantity', sa.Integer(), nullable=True),
    sa.Column('bsr_rank', sa.Integer(), nullable=True),
    sa.Column('parent_asin', sa.String(length=16), nullable=True),
    sa.Column('main_image_url', sa.String(length=1024), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores_store.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listing_snapshot_date', 'amazon_listing_snapshots', ['snapshot_date'], unique=False)
    op.create_index('ix_listing_snapshot_sku', 'amazon_listing_snapshots', ['store_id', 'sku'], unique=False)
    op.create_index('ix_listing_snapshot_store_asin', 'amazon_listing_snapshots', ['store_id', 'asin'], unique=False)
    op.create_table('amazon_report_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('report_type', sa.String(length=128), nullable=False),
    sa.Column('data_start_time', sa.DateTime(), nullable=True),
    sa.Column('data_end_time', sa.DateTime(), nullable=True),
    sa.Column('report_id', sa.String(length=128), nullable=True),
    sa.Column('document_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('processing_status', sa.String(length=32), nullable=True),
    sa.Column('result_location', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores_store.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'report_type', 'data_start_time', 'data_end_time', name='uq_report_task_unique')
    )
    op.create_index('ix_report_task_report_id', 'amazon_report_tasks', ['report_id'], unique=False)
    op.create_index('ix_report_task_store_status', 'amazon_report_tasks', ['store_id', 'status'], unique=False)
    op.create_table('asset_groups',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('shop_id', sa.String(length=64), server_default='', nullable=False),
    sa.Column('createdAt', sa.String(length=64), nullable=False),
    sa.Column('updatedAt', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['stores_store.id'], name='fk_asset_groups_shop_id_stores_store', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_groups_shop_id'), 'asset_groups', ['shop_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('videoUrl', sa.Text(), nullable=True),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('productId', sa.String(length=64), nullable=True),
    sa.Column('productName', sa.String(length=255), nullable=True),
    sa.Column('asin', sa.String(length=32), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('groups', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('shop_id', sa.String(length=64), server_default='', nullable=False),
    sa.Column('createdAt', sa.String(length=64), nullable=False),
    sa.Column('updatedAt', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['stores_store.id'], name='fk_assets_shop_id_stores_store', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_shop_id'), 'assets', ['shop_id'], unique=False)
    op.create_table('candidate_groups',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('shop_id', sa.String(length=64), server_default='', nullable=False),
    sa.Column('createdAt', sa.String(length=64), nullable=False),
    sa.Column('updatedAt', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['stores_store.id'], name='fk_candidate_groups_shop_id_stores_store', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_groups_shop_id'), 'candidate_groups', ['shop_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('asin', sa.String(length=32), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('sub_category', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('site', sa.String(length=64), nullable=True),
    sa.Column('estimated_monthly_sales', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('bsr', sa.Integer(), nullable=True),
    sa.Column('bsr_category', sa.String(length=64), nullable=True),
    sa.Column('listed_date', sa.String(length=64), nullable=True),
    sa.Column('roi_estimated', sa.Float(), nullable=False),
    sa.Column('margin', sa.Float(), nullable=False),
    sa.Column('blue_ocean_score', sa.Integer(), nullable=False),
    sa.Column('overall_listing_score', sa.Integer(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('competitor_asins', sa.JSON(), nullable=True),
    sa.Column('selling_points', sa.Text(), nullable=True),
    sa.Column('main_image', sa.Text(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=False),
    sa.Column('reviewed_at', sa.String(length=64), nullable=True),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('monitor_data', sa.JSON(), nullable=True),
    sa.Column('last_monitored_at', sa.String(length=64), nullable=True),
    sa.Column('shop_id', sa.String(length=64), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('groups', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['stores_store.id'], name='fk_candidates_shop_id_stores_store', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_asin'), 'candidates', ['asin'], unique=False)
    op.create_index(op.f('ix_candidates_review_status'), 'candidates', ['review_status'], unique=False)
    op.create_index(op.f('ix_candidates_shop_id'), 'candidates', ['shop_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('shop_id', sa.String(length=64), nullable=True),
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['stores_store.id'], name='fk_conversations_shop_id_stores_store', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_owner_id'), 'conversations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_conversations_shop_id'), 'conversations', ['shop_id'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('shop_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['stores_store.id'], name='fk_knowledge_bases_shop_id_stores_store', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_bases_shop_id'), 'knowledge_bases', ['shop_id'], unique=False)
    op.create_table('knowledge_docs',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('shop_id', sa.String(length=64), nullable=False),
    sa.Column('kb_id', sa.String(length=160), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['stores_store.id'], name='fk_knowledge_docs_shop_id_stores_store', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_docs_kb_id'), 'knowledge_docs', ['kb_id'], unique=False)
    op.create_index(op.f('ix_knowledge_docs_shop_id'), 'knowledge_docs', ['shop_id'], unique=False)
    op.create_table('knowledge_faqs',
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('shop_id', sa.String(length=64), nullable=False),
    sa.Column('kb_id', sa.String(length=160), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['stores_store.id'], name='fk_knowledge_faqs_shop_id_stores_store', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_faqs_category'), 'knowledge_faqs', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_faqs_kb_id'), 'knowledge_faqs', ['kb_id'], unique=False)
    op.create_index(op.f('ix_knowledge_faqs_shop_id'), 'knowledge_faqs', ['shop_id'], unique=False)
    op.create_index(op.f('ix_knowledge_faqs_status'), 'knowledge_faqs', ['status'], unique=False)
    op.create_table('monitor_groups',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('shop_id', sa.String(length=64), nullable=False),
    sa.Column('createdAt', sa.String(length=64), nullable=False),
    sa.Column('updatedAt', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['stores_store.id'], name='fk_monitor_groups_shop_id_stores_store', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_groups_shop_id'), 'monitor_groups', ['shop_id'], unique=False)
    op.create_table('monitors',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('asin', sa.String(length=32), nullable=False),
    sa.Column('shop_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=False),
    sa.Column('main_image', sa.Text(), nullable=False),
    sa.Column('marketplace', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('latest_price', sa.Float(), nullable=False),
    sa.Column('price_change_7d', sa.Float(), nullable=False),
    sa.Column('latest_bsr', sa.Integer(), nullable=False),
    sa.Column('bsr_category', sa.String(length=128), nullable=False),
    sa.Column('bsr_change_7d', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('reviews_added_7d', sa.Integer(), nullable=False),
    sa.Column('stock_status', sa.String(length=16), nullable=False),
    sa.Column('estimated_units_remaining', sa.Integer(), nullable=True),
    sa.Column('est_monthly_sales', sa.Integer(), nullable=False),
    sa.Column('price_history', sa.JSON(), nullable=True),
    sa.Column('bsr_history', sa.JSON(), nullable=True),
    sa.Column('review_events', sa.JSON(), nullable=True),
    sa.Column('variations', sa.JSON(), nullable=True),
    sa.Column('listing_changes', sa.JSON(), nullable=True),
    sa.Column('group_ids', sa.JSON(), nullable=True),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('source_candidate_id', sa.String(length=64), nullable=True),
    sa.Column('owned_by', sa.JSON(), nullable=True),
    sa.Column('added_at', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['stores_store.id'], name='fk_monitors_shop_id_stores_store', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'asin', name='uq_monitor_shop_asin')
    )
    op.create_index(op.f('ix_monitors_asin'), 'monitors', ['asin'], unique=False)
    op.create_index(op.f('ix_monitors_shop_id'), 'monitors', ['shop_id'], unique=False)
    op.create_table('platform_rule_docs',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('shop_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['stores_store.id'], name='fk_platform_rule_docs_shop_id_stores_store', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_rule_docs_platform'), 'platform_rule_docs', ['platform'], unique=False)
    op.create_index(op.f('ix_platform_rule_docs_shop_id'), 'platform_rule_docs', ['shop_id'], unique=False)
    op.create_table('platform_rules',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('shop_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.String(length=32), nullable=False),
    sa.Column('expiry_date', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_doc_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['stores_store.id'], name='fk_platform_rules_shop_id_stores_store', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_rules_category'), 'platform_rules', ['category'], unique=False)
    op.create_index(op.f('ix_platform_rules_platform'), 'platform_rules', ['platform'], unique=False)
    op.create_index(op.f('ix_platform_rules_shop_id'), 'platform_rules', ['shop_id'], unique=False)
    op.create_index(op.f('ix_platform_rules_source_doc_id'), 'platform_rules', ['source_doc_id'], unique=False)
    op.create_table('product_groups',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('shop_id', sa.String(length=64), server_default='', nullable=False),
    sa.Column('createdAt', sa.String(length=64), nullable=False),
    sa.Column('updatedAt', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['stores_store.id'], name='fk_product_groups_shop_id_stores_store', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_groups_shop_id'), 'product_groups', ['shop_id'], unique=False)
    op.create_table('shop_voice',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('shop_id', sa.String(length=64), nullable=False),
    sa.Column('voice_id', sa.String(length=128), nullable=True),
    sa.Column('target_model', sa.String(length=64), nullable=False),
    sa.Column('voice_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=False),
    sa.Column('sample_url', sa.Text(), nullable=False),
    sa.Column('sample_name', sa.String(length=255), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('sample_duration', sa.Integer(), nullable=False),
    sa.Column('authorized_at', sa.String(length=64), nullable=False),
    sa.Column('authorized_by', sa.String(length=36), nullable=False),
    sa.Column('agreement_snapshot', sa.Text(), nullable=False),
    sa.Column('preview_text', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.String(length=64), nullable=False),
    sa.Column('updatedAt', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['stores_store.id'], name='fk_shop_voice_shop_id_stores_store', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_voice_shop_id'), 'shop_voice', ['shop_id'], unique=False)
    op.create_index(op.f('ix_shop_voice_status'), 'shop_voice', ['status'], unique=False)
    op.create_index('uq_shop_voice_shop', 'shop_voice', ['shop_id'], unique=True)
    op.create_table('spus',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('sub_category', sa.String(length=64), nullable=False),
    sa.Column('spu_theme', sa.String(length=32), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('selling_points', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('main_image', sa.Text(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('spu_common', sa.JSON(), nullable=True),
    sa.Column('shop_id', sa.String(length=64), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('groups', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['stores_store.id'], name='fk_spus_shop_id_stores_store', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spus_shop_id'), 'spus', ['shop_id'], unique=False)
    op.create_table('skus',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('spu_id', sa.String(length=64), nullable=False),
    sa.Column('spec_value', sa.String(length=64), nullable=True),
    sa.Column('asin', sa.String(length=32), nullable=False),
    sa.Column('sku_code', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('site', sa.String(length=64), nullable=True),
    sa.Column('fba_stock', sa.Integer(), nullable=False),
    sa.Column('fbm_stock', sa.Integer(), nullable=False),
    sa.Column('fulfillment_type', sa.String(length=8), nullable=False),
    sa.Column('bsr', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('daily_sales_avg', sa.Float(), nullable=False),
    sa.Column('roi', sa.Float(), nullable=False),
    sa.Column('margin', sa.Float(), nullable=False),
    sa.Column('listing_status', sa.String(length=16), nullable=False),
    sa.Column('generated_title', sa.Text(), nullable=True),
    sa.Column('generated_bullets', sa.JSON(), nullable=True),
    sa.Column('generated_a_plus', sa.JSON(), nullable=True),
    sa.Column('seo_score', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.String(length=64), nullable=True),
    sa.Column('listing_version', sa.Integer(), nullable=False),
    sa.Column('listing_history', sa.JSON(), nullable=True),
    sa.Column('has_a_plus', sa.Boolean(), nullable=False),
    sa.Column('has_video', sa.Boolean(), nullable=False),
    sa.Column('rating_breakdown', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['spu_id'], ['spus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skus_asin'), 'skus', ['asin'], unique=False)
    op.create_index(op.f('ix_skus_spu_id'), 'skus', ['spu_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skus_spu_id'), table_name='skus')
    op.drop_index(op.f('ix_skus_asin'), table_name='skus')
    op.drop_table('skus')
    op.drop_index(op.f('ix_spus_shop_id'), table_name='spus')
    op.drop_table('spus')
    op.drop_index('uq_shop_voice_shop', table_name='shop_voice')
    op.drop_index(op.f('ix_shop_voice_status'), table_name='shop_voice')
    op.drop_index(op.f('ix_shop_voice_shop_id'), table_name='shop_voice')
    op.drop_table('shop_voice')
    op.drop_index(op.f('ix_product_groups_shop_id'), table_name='product_groups')
    op.drop_table('product_groups')
    op.drop_index(op.f('ix_platform_rules_source_doc_id'), table_name='platform_rules')
    op.drop_index(op.f('ix_platform_rules_shop_id'), table_name='platform_rules')
    op.drop_index(op.f('ix_platform_rules_platform'), table_name='platform_rules')
    op.drop_index(op.f('ix_platform_rules_category'), table_name='platform_rules')
    op.drop_table('platform_rules')
    op.drop_index(op.f('ix_platform_rule_docs_shop_id'), table_name='platform_rule_docs')
    op.drop_index(op.f('ix_platform_rule_docs_platform'), table_name='platform_rule_docs')
    op.drop_table('platform_rule_docs')
    op.drop_index(op.f('ix_monitors_shop_id'), table_name='monitors')
    op.drop_index(op.f('ix_monitors_asin'), table_name='monitors')
    op.drop_table('monitors')
    op.drop_index(op.f('ix_monitor_groups_shop_id'), table_name='monitor_groups')
    op.drop_table('monitor_groups')
    op.drop_index(op.f('ix_knowledge_faqs_status'), table_name='knowledge_faqs')
    op.drop_index(op.f('ix_knowledge_faqs_shop_id'), table_name='knowledge_faqs')
    op.drop_index(op.f('ix_knowledge_faqs_kb_id'), table_name='knowledge_faqs')
    op.drop_index(op.f('ix_knowledge_faqs_category'), table_name='knowledge_faqs')
    op.drop_table('knowledge_faqs')
    op.drop_index(op.f('ix_knowledge_docs_shop_id'), table_name='knowledge_docs')
    op.drop_index(op.f('ix_knowledge_docs_kb_id'), table_name='knowledge_docs')
    op.drop_table('knowledge_docs')
    op.drop_index(op.f('ix_knowledge_bases_shop_id'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_conversations_shop_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_owner_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_candidates_shop_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_review_status'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_asin'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_candidate_groups_shop_id'), table_name='candidate_groups')
    op.drop_table('candidate_groups')
    op.drop_index(op.f('ix_assets_shop_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_asset_groups_shop_id'), table_name='asset_groups')
    op.drop_table('asset_groups')
    op.drop_index('ix_report_task_store_status', table_name='amazon_report_tasks')
    op.drop_index('ix_report_task_report_id', table_name='amazon_report_tasks')
    op.drop_table('amazon_report_tasks')
    op.drop_index('ix_listing_snapshot_store_asin', table_name='amazon_listing_snapshots')
    op.drop_index('ix_listing_snapshot_sku', table_name='amazon_listing_snapshots')
    op.drop_index('ix_listing_snapshot_date', table_name='amazon_listing_snapshots')
    op.drop_table('amazon_listing_snapshots')
    op.drop_index('ix_inv_health_store_date', table_name='amazon_inventory_health')
    op.drop_index('ix_inv_health_stockout', table_name='amazon_inventory_health')
    op.drop_index('ix_inv_health_stagnant', table_name='amazon_inventory_health')
    op.drop_table('amazon_inventory_health')
    op.drop_index('ix_daily_sales_store_date', table_name='amazon_daily_sales')
    op.drop_index('ix_daily_sales_date', table_name='amazon_daily_sales')
    op.drop_index('ix_daily_sales_asin', table_name='amazon_daily_sales')
    op.drop_table('amazon_daily_sales')
    op.drop_index('ix_amazon_creds_store_id', table_name='amazon_credentials')
    op.drop_index('ix_amazon_creds_status', table_name='amazon_credentials')
    op.drop_table('amazon_credentials')
    op.drop_index('ix_comp_snap_store_date', table_name='amazon_competitor_snapshots')
    op.drop_index('ix_comp_snap_competes', table_name='amazon_competitor_snapshots')
    op.drop_index('ix_comp_snap_brand', table_name='amazon_competitor_snapshots')
    op.drop_table('amazon_competitor_snapshots')
    op.drop_index('ix_amazon_auth_logs_store_id', table_name='amazon_auth_logs')
    op.drop_index('ix_amazon_auth_logs_created', table_name='amazon_auth_logs')
    op.drop_index('ix_amazon_auth_logs_action', table_name='amazon_auth_logs')
    op.drop_table('amazon_auth_logs')
    op.drop_index('ix_ad_metrics_store_date', table_name='amazon_ad_metrics')
    op.drop_index('ix_ad_metrics_report_type', table_name='amazon_ad_metrics')
    op.drop_index('ix_ad_metrics_campaign', table_name='amazon_ad_metrics')
    op.drop_index('ix_ad_metrics_asin', table_name='amazon_ad_metrics')
    op.drop_table('amazon_ad_metrics')
    op.drop_index('uq_aigc_jobs_inflight', table_name='aigc_jobs', postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.drop_index(op.f('ix_aigc_jobs_user_id'), table_name='aigc_jobs')
    op.drop_index('ix_aigc_jobs_user_created', table_name='aigc_jobs')
    op.drop_index(op.f('ix_aigc_jobs_status'), table_name='aigc_jobs')
    op.drop_index(op.f('ix_aigc_jobs_shop_id'), table_name='aigc_jobs')
    op.drop_index(op.f('ix_aigc_jobs_kind'), table_name='aigc_jobs')
    op.drop_index(op.f('ix_aigc_jobs_dedupe_key'), table_name='aigc_jobs')
    op.drop_table('aigc_jobs')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_stores_store_owner_id'), table_name='stores_store')
    op.drop_table('stores_store')
    op.drop_index(op.f('ix_shops_owner_id'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_payment_methods_user_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_idempotency_key'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_index('ix_conv_msg_conversation_seq', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    # ### end Alembic commands ###

    # ================================================================
    #  ★★ 必须显式删除 PG 的 ENUM 类型 —— 这是 op.drop_table **不会**做的。
    #
    #  为什么：SQLAlchemy 在 create_table 时会自动 `CREATE TYPE`（例如
    #    users.role -> userrole），但 downgrade 侧的 op.drop_table 只发
    #    `DROP TABLE`，**不会连带 DROP TYPE**（PG 也没有级联删类型的语义）。
    #
    #  漏掉这一步的实测后果（探针 script-r51_ci_migration_dryrun.py）：
    #      downgrade base   -> exit=0（看起来成功）
    #      upgrade head     -> sqlalchemy.exc.ProgrammingError:
    #                          type "userrole" already exists
    #    ⇒ **降级不可逆**，而「降级再升回」恰恰是迁移链验证的核心步骤。
    #
    #  ★ 类型名是 data-driven 实测得出的（pg_enum + pg_namespace 查 public），
    #    不是照 ORM 里的类名猜的：ORM 里叫 UserRole / ShopPlatform，
    #    库里的类型名是小写的 userrole / shopplatform。
    #    （PlanType 虽然也是 str,Enum，但没有被任何列用作 SAEnum ⇒ 库里无此类型。）
    #
    #  ★ 用 IF EXISTS：对「从未建过类型」的库（理论上不会出现）保持幂等，
    #    不会因为多一次 DROP 而中断整个降级。
    # ================================================================
    op.execute("DROP TYPE IF EXISTS userrole")
    op.execute("DROP TYPE IF EXISTS shopplatform")
