"""add parent_content and widen variation_parent

Revision ID: 330c6bbf4c9e
Revises: 5fe72f9a9520
Create Date: 2026-09-09 13:34:30.099124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '330c6bbf4c9e'
down_revision: Union[str, Sequence[str], None] = '5fe72f9a9520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('parent_content', sa.JSON(), nullable=True))
    op.alter_column('products', 'variation_parent',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'variation_parent',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.drop_column('products', 'parent_content')
    # ### end Alembic commands ###
