"""auth: accounts/members/tokens/login_attempts + users 撤销与锁定列 + stores 归属与凭证列

Revision ID: d1e2f3a4b5c6
Revises: a506249ae3e3
Create Date: 2026-09-16 13:15:19.710854

==============================================================================
内容（P1-b / P1-c，2026-09-16）
==============================================================================
1. `users` 加三列：token_version（整批撤销）、failed_login_count + locked_until（爆破锁定）
2. 新表 `accounts` / `account_members` —— 「正式建 account → store 层级」的落点
3. 新表 `email_tokens`（邮箱验证 / 密码重置，只存 sha256）/ `login_attempts`（登录审计）
4. `stores_store` 加 `account_id`（归属锚点）与 `api_credentials`（Fernet 密文）
5. **数据回填**：为每个「拥有店铺」的用户建个人账户，把店铺挂上去，并补 owner 成员记录

==============================================================================
★★★ 生成本迁移时踩到的坑（别重蹈，2026-09-16）
==============================================================================
本文件第一次生成时**整段漏掉了 4 张新表的 create_table**，只留下加列和一条
指向 `accounts` 的外键。原因不是 autogenerate 有 bug，而是：

    开发服务器（`uvicorn main:app --reload`）一直开着
      ⇒ 改完 ORM 模型文件，reloader 立刻重启应用
      ⇒ lifespan 调 `init_db()`
      ⇒ development 分支走 `Base.metadata.create_all`
      ⇒ **4 张新表被抢先建进开发库**
      ⇒ 随后 `alembic revision --autogenerate` 对着开发库比对，
         看到表已存在 ⇒ 判定"无需建表" ⇒ 静默漏掉

后果的严重性在于**它在本机看不出来**：
  · 本机 `alembic upgrade head` 能跑通（表早被 create_all 建好了）
  · 全新库 / CI / 生产 `upgrade head` 直接失败在
    `create_foreign_key(... 'accounts' ...)` ⇒ 报错指向**外键**，
    极易被误判成"外键名写错了"，而真因是"压根没建表"。

⇒ 固化两条规则：
  ① **做 schema 变更前先停掉 reload 开发服务**（或至少别在它开着时 autogenerate）；
  ② 生成迁移必须对着一个「只跑过 alembic、从没跑过 create_all」的库。
     本次用探针库 `ecommerce_r90probe`（先 `upgrade head` 再 autogenerate）。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e2f3a4b5c6'
down_revision: Union[str, Sequence[str], None] = 'a506249ae3e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ====== 回填 SQL（upgrade 用，downgrade 不逆向，理由见 downgrade docstring）======
#
# ★ 三条都幂等：重复执行不会造出第二个账户、第二条 owner 成员记录。
#   幂等的意义：这类迁移偶尔会被人工重跑（中途失败后手工续跑），
#   非幂等 SQL 会造出重复账户 —— 而重复账户**不会报错**，
#   只会让用户在界面上看到两个一模一样的团队。
#
# ★ 只处理 `owner_id IS NOT NULL` 的店铺：
#   owner_id 为空的是「无主店铺」（历史遗留 / 测试合成店铺），
#   没有一个可信的人可以当账户所有者，硬塞一个 owner 反而会**制造越权**。
#   这些店铺的 account_id 保持 NULL，由应用侧兜底分支处理
#   （见 core/tenant/middleware.py::_resolve_current_shop_id 的 owner_id 回退）。
#
# ★ `gen_random_uuid()` 是 PostgreSQL 13+ 内置（不需要 pgcrypto 扩展）。
#   本项目基线是 postgres:15-alpine。
_BACKFILL_ACCOUNTS = """
INSERT INTO accounts (id, name, owner_user_id, is_active, created_at, updated_at)
SELECT gen_random_uuid()::text,
       COALESCE(NULLIF(u.name, ''), split_part(u.email, '@', 1)) || ' 的账户',
       u.id, true, now(), now()
FROM users u
WHERE EXISTS (SELECT 1 FROM stores_store s WHERE s.owner_id = u.id)
  AND NOT EXISTS (SELECT 1 FROM accounts a WHERE a.owner_user_id = u.id)
"""

_BACKFILL_STORE_LINKS = """
UPDATE stores_store s
SET account_id = a.id
FROM accounts a
WHERE a.owner_user_id = s.owner_id
  AND s.account_id IS NULL
"""

_BACKFILL_OWNER_MEMBERS = """
INSERT INTO account_members (id, account_id, user_id, role, status, created_at, joined_at)
SELECT gen_random_uuid()::text, a.id, a.owner_user_id, 'owner', 'active', now(), now()
FROM accounts a
WHERE NOT EXISTS (
    SELECT 1 FROM account_members m
    WHERE m.account_id = a.id AND m.user_id = a.owner_user_id
)
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name='fk_accounts_owner_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_owner_user_id'), 'accounts', ['owner_user_id'], unique=False)
    op.create_table('email_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=24), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('requested_ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_email_tokens_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_tokens_token_hash'), 'email_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_tokens_user_id'), 'email_tokens', ['user_id'], unique=False)
    op.create_index('ix_email_tokens_user_purpose', 'email_tokens', ['user_id', 'purpose'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_login_attempts_user_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_created_at'), 'login_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.create_index('ix_login_attempts_email_created', 'login_attempts', ['email', 'created_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_user_id'), 'login_attempts', ['user_id'], unique=False)
    op.create_table('account_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='fk_account_members_account_id_accounts', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name='fk_account_members_invited_by_users', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_account_members_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'user_id', name='uq_account_members_account_user')
    )
    op.create_index(op.f('ix_account_members_account_id'), 'account_members', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_members_user_id'), 'account_members', ['user_id'], unique=False)
    op.create_index('ix_account_members_user_status', 'account_members', ['user_id', 'status'], unique=False)
    op.add_column('stores_store', sa.Column('account_id', sa.String(length=36), nullable=True))
    op.add_column('stores_store', sa.Column('api_credentials', sa.Text(), nullable=True, comment='Fernet 密文（enc:v1: 前缀），禁止明文'))
    op.create_index(op.f('ix_stores_store_account_id'), 'stores_store', ['account_id'], unique=False)
    # ★ 必须排在 create_table('accounts') 之后 —— 顺序反了就是文件头记录的那个报错形态
    op.create_foreign_key('fk_stores_store_account_id_accounts', 'stores_store', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

    # ====== 数据回填（对全新空库是 no-op；对既有库把存量店铺接进账户层）======
    op.execute(_BACKFILL_ACCOUNTS)
    op.execute(_BACKFILL_STORE_LINKS)
    op.execute(_BACKFILL_OWNER_MEMBERS)


def downgrade() -> None:
    """
    Downgrade schema.

    ⚠️ 回填**不逆向**：本迁移把店铺从「按 owner_id 归属」改成「按 account_id 归属」，
       而 owner_id 一直在、从未被改动过 ⇒ 回滚后应用又按 owner_id 判定，
       语义可以干净回退。若这里再写一段「把 account_id 清空」，反而会制造
       回滚后的不一致（账户层还在、店铺却没了归属）。
       账户/成员数据随表一起 drop，不留残渣。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_count')
    op.drop_column('users', 'token_version')
    op.drop_constraint('fk_stores_store_account_id_accounts', 'stores_store', type_='foreignkey')
    op.drop_index(op.f('ix_stores_store_account_id'), table_name='stores_store')
    op.drop_column('stores_store', 'api_credentials')
    op.drop_column('stores_store', 'account_id')
    op.drop_index('ix_account_members_user_status', table_name='account_members')
    op.drop_index(op.f('ix_account_members_user_id'), table_name='account_members')
    op.drop_index(op.f('ix_account_members_account_id'), table_name='account_members')
    op.drop_table('account_members')
    op.drop_index(op.f('ix_login_attempts_user_id'), table_name='login_attempts')
    op.drop_index('ix_login_attempts_email_created', table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_created_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index('ix_email_tokens_user_purpose', table_name='email_tokens')
    op.drop_index(op.f('ix_email_tokens_user_id'), table_name='email_tokens')
    op.drop_index(op.f('ix_email_tokens_token_hash'), table_name='email_tokens')
    op.drop_table('email_tokens')
    op.drop_index(op.f('ix_accounts_owner_user_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
